#pragma once

#define SNAKE_INIT_LENGTH 3
#define SNAKE_MAX_LENGTH WORLD_WIDTH * WORLD_HEIGHT

#define WORLD_WIDTH 20
#define WORLD_HEIGHT 20
#define WORLD_CELL_SIZE 20

#define WINDOW_WIDTH WORLD_WIDTH * WORLD_CELL_SIZE
#define WINDOW_HEIGHT WORLD_HEIGHT * WORLD_CELL_SIZE
